# Generated by Django 5.2 on 2025-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.CharField(default='default_user', max_length=128),
            preserve_default=False,
        ),
    ]
