# Generated by Django 5.2 on 2025-04-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_firebaseuser_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
