# Generated by Django 5.2 on 2025-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_firebaseuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='creator_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
